apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: opentelemetry-operator
spec:
  mode: deployment
  service:
    type: ClusterIP
    ports:
      - name: otlp-grpc
        port: 4317
      - name: otlp-http
        port: 4318
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      debug:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug]
