server:
  global:
    scrape_interval: 15s

  extraScrapeConfigs:
  - job_name: 'otel-collector'
    static_configs:
    - targets: [ 'otel-collector-collector.observability.svc.cluster.local:8889' ]
