resources:
  - deployment.yml

configMapGenerator:
  - name: grafana-provisioning
    files:
      - ./provisioning/datasources.yml
      - ./provisioning/dashboards.yml
      - ./provisioning/dashboard_19419.json

generatorOptions:
  disableNameSuffixHash: true
