apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TineoC/otel-demo
    path: ./deploy/services/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
