apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http:
            endpoint: "0.0.0.0:4318"
            cors:
              allowed_origins: ["*"]
              allowed_headers: ["*"]
              max_age: 7200

    exporters:
      debug:
      otlp/tempo:
        endpoint: "tempo.observability.svc.cluster.local:4317"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug, otlp/tempo]
