apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http:
            endpoint: "0.0.0.0:4318"
            cors:
              allowed_origins: ["*"]
              allowed_headers: ["*"]
              max_age: 7200

    processors:
      log-traces:
        sampling_initial: 1
        sampling_thereafter: 1

    exporters:
      otlp/tempo:
        endpoint: "tempo.observability.svc.cluster.local:9095"
        tls:
          insecure: true
      debug:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [log-traces]
          exporters: [debug, otlp/tempo]
