apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  image: otel/opentelemetry-collector-contrib:0.90.1
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
            cors:
              allowed_origins: ["*"]
              allowed_headers: ["*"]
              max_age: 7200

    processors:
      batch: {}
      spanmetrics:
        metrics_exporter: prometheus

    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: "tempo.observability.svc.cluster.local:4317"
        tls:
          insecure: true
      prometheus:
        endpoint: "otel-collector-collector.observability.svc.cluster.local:8889"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [spanmetrics, batch]
          exporters: [otlp, debug]

        metrics:
          # receivers: [spanmetrics]
          processors: [batch]
          exporters: [prometheus]
