apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
            cors:
              allowed_origins: ["*"]
              allowed_headers: ["*"]
              max_age: 7200

    processors:
      batch: {}

    exporters:
      debug: {}
      otlphttp:
        endpoint: "http://tempo.observability.svc.cluster.local:4318"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, otlphttp]
