apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  image: otel/opentelemetry-collector-contrib:0.90.1
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
            cors:
              allowed_origins: ["*"]
              allowed_headers: ["*"]
              max_age: 7200

    connectors:
      spanmetrics/full:
        namespace: traces.span.metrics

    processors:
      batch: {}

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      debug:
        verbosity: basic
      otlp:
        endpoint: "tempo.observability.svc.cluster.local:4317"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [spanmetrics/full, otlp, debug]
        metrics:
          receivers: [spanmetrics/full]
          processors: [batch]
          exporters: [prometheus]
