apiVersion: v1
kind: Service
metadata:
  name: otel-collector-prometheus
  namespace: observability
spec:
  selector:
    app.kubernetes.io/component: opentelemetry-collector
  ports:
  - name: prometheus
    port: 8889
    targetPort: 8889
