# deploy/monitoring/tempo/config.yml
server:
  http_listen_port: 3200
  grpc_listen_port: 4317

distributor:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

ingester:
  # wal:
  #   path: /var/tempo/wal
  trace:
    backend: local
    local:
      path: /var/tempo/traces
  max_chunk_age: 2h
  lifecycler:
    ring:
      replication_factor: 1
      kvstore:
        store: memberlist
    unregister_on_shutdown: true

querier: # all defaults are fine here, you can omit this block entirely

blocks_storage:
  backend: filesystem
  tsdb:
    wal:
      enabled: true
      dir: /data/wal

memberlist:
  join_members: []
