# deploy/monitoring/tempo/config.yml
auth_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 4317

distributor:
  receivers:
    otlp:
      protocols:
        grpc: {} # will listen on 0.0.0.0:4317
        http: {} # will listen on 0.0.0.0:4318

storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/traces
