auth_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317
ingester:
  lifecycler:
    ring:
      replication_factor: 1
      kvstore:
        store: memberlist
  trace_idle_period: 10s
  flush_check_period: 10s

compactor:
  compaction:
    compaction_window: 1h
    block_retention: 1h
    compacted_block_retention: 10m

querier: {}

storage:
  trace:
    backend: local # backend configuration to use
    wal:
      path: /tmp/tempo/wal # where to store the the wal locally
    local:
      path: /tmp/tempo
    pool:
      max_workers: 100 # the worker pool mainly drives querying, but is also used for polling the blocklist
      queue_depth: 10000

memberlist:
  join_members:
  - tempo-headless.observability.svc.cluster.local