# deploy/monitoring/tempo/config.yml
auth_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 4317

server:
  http_listen_port: 3200
  grpc_listen_port: 4317

distributor:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

ingester:
  # where spans get written
  wal:
    path: /var/tempo/wal
  trace:
    backend: local
    local:
      path: /var/tempo/traces
  lifecycler:
    ring:
      replication_factor: 1
      kvstore:
        store: memberlist
    unregister_on_shutdown: true

querier:

memberlist:
  # single‐node ring (no peers)
  join_members: []