server:
  http_listen_port: 3200

receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

distributor: {}

ingester:
  wal:
    path: /var/tempo/wal
  trace:
    backend: local
    local:
      path: /var/tempo/traces

querier:
  search_backend: local

memberlist:
  join_members: []
