# deploy/monitoring/tempo/config.yml
server:
  http_listen_port: 3200
  grpc_listen_port: 4317

distributor:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

ingester:
  # wal:
  #   path: /var/tempo/wal
  # trace:
  #   backend: local
  #   local:
  #     path: /var/tempo/traces
  # lifecycler:
  #   ring:
  #     replication_factor: 1
  #     kvstore:
  #       store: memberlist
    # unregister_on_shutdown: true

querier: # all defaults are fine here, you can omit this block entirely

storage:
  trace:
    backend: local # backend configuration to use
    wal:
      path: /tmp/tempo/wal # where to store the the wal locally
      bloom_filter_false_positive: 0.05 # bloom filter false positive rate.  lower values create larger filters but fewer false positives
      index_downsample: 10 # number of traces per index record
    local:
      path: /tmp/tempo
    pool:
      max_workers: 100 # the worker pool mainly drives querying, but is also used for polling the blocklist
      queue_depth: 10000

memberlist:
  join_members: []
