auth_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 4317

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

ingester:

compactor:
  compaction:
    compaction_window: 1h # blocks in this time window will be compacted together
    max_compaction_objects: 1000000 # maximum size of compacted blocks
    block_retention: 1h
    compacted_block_retention: 10m

storage:
  trace:
    backend: local # backend configuration to use
    wal:
      path: /tmp/tempo/wal # where to store the the wal locally
    local:
      path: /tmp/tempo
    pool:
      max_workers: 100 # the worker pool mainly drives querying, but is also used for polling the blocklist
      queue_depth: 10000