apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring

resources:
  - ./grafana
  - ./otel
  - ./tempo

labels:
  - pairs:
      role: monitoring

helmCharts:
  - name: prometheus
      repo: https://prometheus-community.github.io/helm-charts
      version: 27.16.0
      releaseName: prometheus
      namespace: observability
      valuesFile: ./prometheus/values.yaml
