name: Push store-frontend to GHCR

on:
  push:
    # paths:
    #   - 'services/frontend/**'
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "$GHCR_PAT" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push store-frontend
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$OWNER_LC/store-frontend:latest ./services/frontend
          docker push ghcr.io/$OWNER_LC/store-frontend:latest
      