name: Push store-frontend to GHCR

on:
  push:
    paths:
      - 'services/frontend/**'
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push store-frontend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/store-frontend:latest ./services/frontend
          docker push ghcr.io/${{ github.repository_owner }}/store-frontend:latest
